name: Build

on: [ push, pull_request ]

permissions:
  contents: read  # to fetch code (actions/checkout)

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [default]
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: v0.67.2
          cache: true
          environments: ${{ matrix.environment }}
      - name: Build the project
        run: |
          pixi run build 
          echo "Build completed successfully."
